const Images = [
  {image: require('../assets/Properties/Property1.jpg')},
  {image: require('../assets/Properties/Property2.png')},
  {image: require('../assets/Properties/Property3.jpg')},
  {image: require('../assets/Properties/Property4.jpg')},
  {image: require('../assets/Properties/Property5.jpg')},
];
const Marker_Icon = [
  {icon: require('../assets/icons8-ios_filled-Country-House.png')},
  {icon: require('../assets/icons8-m_outlined-Field.png')},
  {icon: require('../assets/icons8-ios_filled-Company.png')},
  {icon: require('../assets/icons8-ios11-House.png')},
  {icon: require('../assets/icons8-ios_filled-Country-House.png')},
];
const f_Icon = [
  {icon: require('../assets/icons8-m_rounded-Occupied-Bed.png')},
  {icon: require('../assets/icons8-pastel_glyph-Bath.png')},
  {icon: require('../assets/icons8-office40-Trigonometry.png')},
];
export const markers = [
  {
    coordinate: {
      latitude: 22.6293867,
      longitude: 88.4254486,
    },
    price: '85 Lakh',
    baseprice: '6000 K/sq.ft',
    address: 'Eden gardens, Mokila, Hyderabad, Telangana',
    feature1: '4 beds',
    feature2: '3 baths',
    feature3: '2452 sqft',
    f1_icon: f_Icon[0].icon,
    f2_icon: f_Icon[1].icon,
    f3_icon: f_Icon[2].icon,
    image: Images[0].image,
    icon: Marker_Icon[0].icon,
  },
  {
    coordinate: {
      latitude: 22.6345648,
      longitude: 88.4377279,
    },
    price: '50 Lakh',
    baseprice: '4400 K/sq.ft',
    address: 'Golkonda Fort, Mokila, Hyderabad, Telangana',
    feature1: '3 beds',
    feature2: '3 baths',
    feature3: '1852 sqft',
    f1_icon: f_Icon[0].icon,
    f2_icon: f_Icon[1].icon,
    f3_icon: f_Icon[2].icon,
    image: Images[1].image,
    icon: Marker_Icon[1].icon,
  },
  {
    coordinate: {
      latitude: 22.6181662,
      longitude: 88.4410113,
    },
    price: '95 Lakh',
    baseprice: '7000 K/sq.ft',
    address: 'Nehru park, Mokila, Hyderabad, Telangana',
    feature1: '6 beds',
    feature2: '5 baths',
    feature3: '4452 sqft',
    f1_icon: f_Icon[0].icon,
    f2_icon: f_Icon[1].icon,
    f3_icon: f_Icon[2].icon,
    image: Images[2].image,
    icon: Marker_Icon[2].icon,
  },
  {
    coordinate: {
      latitude: 22.6041137,
      longitude: 88.4397463,
    },
    price: '45 Lakh',
    baseprice: '4000 K/sq.ft',
    address: 'NTR garden road, Mokila, Hyderabad, Telangana',
    feature1: '4 beds',
    feature2: '2 baths',
    feature3: '2052 sqft',
    f1_icon: f_Icon[0].icon,
    f2_icon: f_Icon[1].icon,
    f3_icon: f_Icon[2].icon,
    image: Images[3].image,
    icon: Marker_Icon[3].icon,
  },
  {
    coordinate: {
      latitude: 22.6292757,
      longitude: 88.444781,
    },
    price: '60 Lakh',
    baseprice: '5000 K/sq.ft',
    address: 'Tangatur Road, Mokila, Hyderabad, Telangana',
    feature1: '4 beds',
    feature2: '4 baths',
    feature3: '2152 sqft',
    f1_icon: f_Icon[0].icon,
    f2_icon: f_Icon[1].icon,
    f3_icon: f_Icon[2].icon,
    image: Images[4].image,
    icon: Marker_Icon[4].icon,
  },
];
